--- 
functional:
- Пользователь должен иметь возможность зарегистрироваться на сайте
- Пользователь должен иметь возможность проводить оценку 
- Пользователь должен иметь возможность добавлять фотографии на сайт
- Пользователь должен иметь возможность поделиться сайтом
- Пользователь должен иметь возможность редактировать данные
- Пользователь должен иметь возможность оплатить заказ
- Пользователь должен иметь возможность оставить отзыв
- Пользователь должен иметь возможность редактировать фотографии
- Пользователь должен иметь возможность просматривать баланс
- Пользователь должен иметь возможность вывода средств
non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен иметь мобильную версию.
implicit:
- Сайт должен быть доступен на различных устройствах
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть визуально-красивым 
...
